name: da-fap-atlas
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - pip
  - jupyterlab
  - ipykernel
  - numpy
  - scipy
  - pandas
  - pyarrow
  - h5py
  - pyyaml
  - requests
  - tqdm
  - matplotlib
  - seaborn
  - plotnine
  - statsmodels
  - scikit-learn
  - networkx
  - scanpy
  - anndata
  - scvi-tools
  - scvelo
  - squidpy
  - scrublet
  - harmonypy
  - bbknn
  - leidenalg
  - python-igraph
  - gseapy
  - decoupler-py
  - mygene
  - r-base
  - r-essentials
  - r-biocmanager
  - r-remotes
  - r-seurat
  - r-harmony
  - r-ggplot2
  - r-patchwork
  - r-data.table
  - r-tidyverse
  - r-yaml
  - bioconductor-singlecellexperiment
  - bioconductor-scran
  - bioconductor-scater
  - bioconductor-limma
  - bioconductor-deseq2
  - bioconductor-gsva
  - bioconductor-clusterprofiler
  - bioconductor-complexheatmap
  - pip:
      - celloracle
      - celltypist
      - liana

